import express, { Request, Response } from 'express';
import { createServer as createViteServer } from 'vite';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { spawn } from 'child_process';
import { GoogleGenAI } from '@google/genai';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = Number(process.env.PORT) || 3000;

app.use(express.json({ limit: '2mb' }));

// Helper to safely execute the Python sandbox
async function executePythonSandbox(payload: any): Promise<any> {
  return new Promise((resolve, reject) => {
    const sandboxPath = path.join(__dirname, 'server', 'sandbox.py');
    const child = spawn('python3', [sandboxPath], {
      timeout: 5000,
      env: { ...process.env, PYTHONUNBUFFERED: '1' }
    });

    let stdoutData = '';
    let stderrData = '';

    child.stdout.on('data', (data) => {
      stdoutData += data.toString();
    });

    child.stderr.on('data', (data) => {
      stderrData += data.toString();
    });

    child.on('error', (err) => {
      reject(new Error(`Failed to start Python process: ${err.message}`));
    });

    child.on('close', (code) => {
      if (code !== 0 && !stdoutData) {
        return reject(new Error(`Python process exited with code ${code}. Stderr: ${stderrData}`));
      }
      try {
        const json = JSON.parse(stdoutData.trim());
        resolve(json);
      } catch (err: any) {
        resolve({
          error: `Output parser error: ${err.message}`,
          raw_output: stdoutData,
          stderr: stderrData
        });
      }
    });

    try {
      child.stdin.write(JSON.stringify(payload));
      child.stdin.end();
    } catch (e: any) {
      reject(new Error(`Failed to write to stdin: ${e.message}`));
    }
  });
}

// API: Run Python Input Validation Test
app.post('/api/execute-python', async (req: Request, res: Response) => {
  try {
    const { scenario_id, test_input, code_vulnerable, code_remediated, is_custom } = req.body;
    const result = await executePythonSandbox({
      scenario_id: scenario_id || 'path_traversal',
      test_input: test_input ?? '',
      code_vulnerable,
      code_remediated,
      is_custom: Boolean(is_custom)
    });
    res.json(result);
  } catch (err: any) {
    console.error('Python execution error:', err);
    res.status(500).json({
      error: err.message,
      trace: [
        {
          step: 'Execution Failure',
          detail: err.message,
          status: 'danger'
        }
      ]
    });
  }
});

// API: Gemini AI Security QA Mentor
app.post('/api/ai-mentor', async (req: Request, res: Response) => {
  try {
    const { code, question, type, challengeTitle } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.json({
        analysis: `⚠️ Gemini API Key not configured in environment. 
Here is standard SecQA Rule Guidance for "${challengeTitle || 'Input Validation'}":
1. **Never trust client input:** Perform strict whitelisting on length, charset, and structure.
2. **Order of Operations:** Unicode Normalization (NFKC) -> Type Parsing -> Validation -> Canonicalization -> Escaping/Parameterization.
3. **Defense in Depth:** Use parameterized queries (SQLite/PostgreSQL) and safe standard libraries (pathlib.Path.resolve, shlex.quote) instead of custom regexes.`
      });
    }

    const ai = new GoogleGenAI({ apiKey });
    const prompt = `You are "SecQA Learn for Dummies", an expert AppSec & Quality Assurance mentor.
Analyze the following code / test scenario for security vulnerabilities and input validation edge cases.

Context / Challenge: ${challengeTitle || 'Code Review'}
Query / Type: ${type || 'general_review'}
User Question: ${question || 'Analyze input validation flaws, edge cases, and provide both QA test cases and security abuse cases.'}

Code snippet under inspection:
\`\`\`
${code || '# No code provided'}
\`\`\`

Respond in structured, beginner-friendly "For Dummies" format:
1. 🎯 **The Core Problem in Plain English** (What goes wrong and why developers make this mistake)
2. ⚡ **Hidden Edge Cases & Dangerous Payloads** (e.g., null bytes, unicode homoglyphs, boundary values, escape sequences)
3. 🧪 **QA Test Cases vs Security Abuse Cases Matrix** (Happy path vs Malicious edge cases)
4. 🛡️ **Remediated Secure Implementation** (Concise secure pattern)
5. 💡 **SecQA Golden Rule** (A memorable 1-sentence takeaway)`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    res.json({
      analysis: response.text || 'No response generated by mentor.'
    });
  } catch (err: any) {
    console.error('AI mentor error:', err);
    res.status(500).json({
      error: `AI Mentor Error: ${err.message}`
    });
  }
});

// Mount Vite or static server
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.join(__dirname, 'dist')));
    app.get('*', (_req, res) => {
      res.sendFile(path.join(__dirname, 'dist', 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`SecQA server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
